version: '3.8'

services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: mysql1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER:        ${DB_USER}
      MYSQL_PASSWORD:    ${DB_PASS}
      MYSQL_DATABASE:    ${DB_NAME}
      MYSQL_ROOT_HOST:   '%'
      # Group Replication settings:
      MYSQL_GROUP_REPLICATION_BOOTSTRAP_GROUP: 'ON'
      MYSQL_GROUP_REPLICATION_START_ON_BOOT:   'ON'
      MYSQL_GROUP_REPLICATION_LOCAL_ADDRESS:   'mysql1:33161'
      MYSQL_GROUP_REPLICATION_GROUP_SEEDS:     'mysql1:33161,mysql2:33161,mysql3:33161'
      MYSQL_GROUP_REPLICATION_GROUP_NAME:      'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
    volumes:
      - mysql1_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql    # monta tu script en initdb.d :contentReference[oaicite:0]{index=0}
    ports:
      - "3307:3306"

  mysql2:
    image: mysql/mysql-server:8.0
    container_name: mysql2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER:        ${DB_USER}
      MYSQL_PASSWORD:    ${DB_PASS}
      MYSQL_DATABASE:    ${DB_NAME}
      MYSQL_ROOT_HOST:   '%'
      MYSQL_GROUP_REPLICATION_BOOTSTRAP_GROUP: 'OFF'
      MYSQL_GROUP_REPLICATION_START_ON_BOOT:   'ON'
      MYSQL_GROUP_REPLICATION_LOCAL_ADDRESS:   'mysql2:33161'
      MYSQL_GROUP_REPLICATION_GROUP_SEEDS:     'mysql1:33161,mysql2:33161,mysql3:33161'
      MYSQL_GROUP_REPLICATION_GROUP_NAME:      'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
    volumes:
      - mysql2_data:/var/lib/mysql
    ports:
      - "3308:3306"

  mysql3:
    image: mysql/mysql-server:8.0
    container_name: mysql3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER:        ${DB_USER}
      MYSQL_PASSWORD:    ${DB_PASS}
      MYSQL_DATABASE:    ${DB_NAME}
      MYSQL_ROOT_HOST:   '%'
      MYSQL_GROUP_REPLICATION_BOOTSTRAP_GROUP: 'OFF'
      MYSQL_GROUP_REPLICATION_START_ON_BOOT:   'ON'
      MYSQL_GROUP_REPLICATION_LOCAL_ADDRESS:   'mysql3:33161'
      MYSQL_GROUP_REPLICATION_GROUP_SEEDS:     'mysql1:33161,mysql2:33161,mysql3:33161'
      MYSQL_GROUP_REPLICATION_GROUP_NAME:      'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
    volumes:
      - mysql3_data:/var/lib/mysql
    ports:
      - "3309:3306"

  router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    restart: unless-stopped
    env_file:
      - .env
    command: >
      --bootstrap root:${DB_PASS}@mysql1:3306 --directory /home/mysqlrouter
    ports:
      - "6446:6446"   # Read-Write endpoint
      - "6447:6447"   # Read-Only endpoint
    volumes:
      - router_data:/home/mysqlrouter
    depends_on:
      - mysql1
      - mysql2
      - mysql3

volumes:
  mysql1_data:
  mysql2_data:
  mysql3_data:
  router_data:
