nfs:
  frontend_network: "172.31.0.0/16"
  server: 172.31.94.237
ip_api: 3.217.29.70
ip_back: 172.31.86.236
app_dir: "/opt/frontend" 
src_dir: "../../middleware" 
dest_dir: "/opt/middleware/"
service_name: "middleware" 

app_entry: "index.js"
nvm_version:  "v0.40.2"
node_major: "22" 
service_user: "{{ ansible_user }}"  