---
- name: Despliege en el del la APP
  hosts: frontend_master
  become: yes

  vars_files:
  - ../vars/vars.yaml
  
  tasks:
    - name: Sincronizar código fuente
      synchronize:
        src:  "../../frontend/delichoc3d"
        dest: "{{ app_dir }}/"
        recursive: yes

    - name: Sustituir CHANGEME → {{ ip_api }}
      replace:
        path: "{{ app_dir }}/delichoc3d/public/config.json"
        regexp: 'CHANGEME'
        replace: "{{ ip_api }}"

    # Instalar dependencias y compilar
    - name: npm install
      command: sudo npm install
      args:
        chdir: "{{ app_dir }}/delichoc3d/"

    # 5) Creamos los ficheros estaticos
    - name: npm run build
      command: npm run build
      args:
        chdir: "{{ app_dir }}/delichoc3d/"

    - name: borrar conteido previo
      ansible.builtin.command: >
        sudo rm -rf /var/www/html/*

    # 6) Publicar dist/ en /var/www/html
    - name: Copiar todo a "/var/www/html"
      shell: sudo cp -r "{{ app_dir }}/delichoc3d/dist/"* /var/www/html

    # 7) Asegurar permisos finales
    - name: Ajustar permisos en "/var/www/html"
      file:
        path: "/var/www/html"
        owner: www-data
        group: www-data
        recurse: yes