---
- name: Despliege del backend
  hosts: backend
  become: yes


  vars_files:
    - ../vars/vars.yaml

  tasks:
    - name : Actulizamos los repositorios
      apt:
        update_cache: yes

    - name: Docker Compose
      apt:
        name: docker-compose
        state: present
    
    # 1) Copiar todo el directorio al servidor
    - name: Sincronizar {{ src_dir }} → {{ dest_dir }}
      synchronize:
        src:  "../../backend"
        dest: "/opt/"
        recursive: yes
        delete: yes

    # 2) Asegurar permisos de ejecución en lanzar.sh
    - name: Dar permisos +x a lanzar.sh
      file:
        path: "/opt/backend/lanzar.sh"
        mode: "0755"

    # 3) Ejecutar el script
    - name: Ejecutar lanzar.sh
      shell: sudo ./lanzar.sh
      args:
        chdir: "/opt/backend"