---
- name: Desplegar middleware Node.js y dejarlo corriendo como servicio
  hosts: middleware
  become: yes
  vars_files:
  - ../vars/vars.yaml

  tasks:
  # Copiar el código al host
  - name: Copiar proyecto al servidor
    synchronize:
      src:  "{{ src_dir }}/"
      dest: "{{ dest_dir }}/"
      recursive: yes
      delete: yes

  #Sustituir CHANGEME en .env
  - name: Reemplazar CHANGEME en .env
    replace:
      path: "{{ dest_dir }}/src/.env"
      regexp: 'CHANGEME'
      replace: "{{ ip_back }}"
      backup: yes

  # Instalacion de cliente mysql
  - name: Instalar cliente MySQL en Debian/Ubuntu
    apt:
      name: default-mysql-client
      state: present
      update_cache: yes

  # Instalacion de node
  - name: Descargar Node.js v22.16.0
    ansible.builtin.get_url:
      url: https://nodejs.org/dist/v22.16.0/node-v22.16.0-linux-x64.tar.xz
      dest: /tmp/node-v22.16.0-linux-x64.tar.xz
      mode: '0644'


  - name: Crear directorio de instalación
    ansible.builtin.file:
      path: /usr/local/node-v22.16.0-linux-x64
      state: directory
      mode: '0755'

  - name: Extraer Node.js en /usr/local
    ansible.builtin.unarchive:
      src: /tmp/node-v22.16.0-linux-x64.tar.xz
      dest: /usr/local
      remote_src: yes


  - name: Ajustar propiedad de los archivos
    ansible.builtin.file:
      path: /usr/local/node-v22.16.0-linux-x64
      owner: root
      group: root
      recurse: yes


  - name: Enlazar binarios en /usr/local/bin
    ansible.builtin.file:
      src: /usr/local/node-v22.16.0-linux-x64/bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
      state: link
      force: yes
    loop:
      - node
      - npm


  - name: npm install
    command: sudo npm install
    args:
      chdir: "{{ dest_dir }}/src"

  # Crear servicio systemd
  - name: Crear servicio systemd {{ service_name }}
    copy:
      dest: "/etc/systemd/system/{{ service_name }}.service"
      mode: "0644"
      content: |
        [Unit]
        Description=Middleware Node.js Service
        After=network.target

        [Service]
        Type=simple
        User=ubuntu
        WorkingDirectory=/opt/middleware/src
        Environment="PATH=/home/ubuntu/.nvm/versions/node/v22.16.0/bin:/usr/bin:/usr/local/bin"
        ExecStart=/usr/local/bin/node /opt/middleware/src/index.js
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target



  # Recargar systemd y arrancar
  - name: Habilitar y arrancar {{ service_name }}
    systemd:
      daemon_reload: yes
      name: "{{ service_name }}"
      enabled: yes
      state: restarted
