---
- name:
  hosts: frontend
  become: yes

  tasks:
    - name : Actulizamos los repositorios
      apt:
        update_cache: yes

    - name : Instalamos el apache
      apt:
        name: apache2
        state: present

    - name: Habilitar el módulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name : Copiamos el el arhcivo 000-default
      copy:
        src: ../conf/000-default.conf
        dest: /etc/apache2/sites-available/
        mode: 0755
    - name: Instalar NVM 
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
      args:
        creates: '\. "$HOME/.nvm/nvm.sh"'

    - name: Instalar Node.js 22 via NVM
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install 22
      args:
        executable: /bin/bash

    - name : Reinicamos el apache
      service:
        name: apache2
        state: restarted

